project_id = "tniionfawnkaecbrhker"

[functions.google-places]
verify_jwt = false

[functions.place-photos]
verify_jwt = false

[functions.lucky-trip-ai]
verify_jwt = false

[functions.external-hotels]
verify_jwt = false

[functions.external-restaurantes]
verify_jwt = false
